name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Lua interpreter
        uses: leafo/gh-actions-lua@v11

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Set up Purescript and spago-legacy
        run: |
          npm i -g purescript
          npm i -g spago-legacy

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: hannesg/ordinary-nix-cache@v0.1.0

      - name: Set up pslua
        run: nix profile install 'github:Unisay/purescript-lua'

      - name: Build and test
        run: ./test.sh
