name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Lua interpreter
        uses: leafo/gh-actions-lua@v11

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Set up Purescript and spago-legacy
        run: |
          npm i -g purescript
          npm i -g spago-legacy

      - name: Download pslua
        run: wget -c https://github.com/Unisay/purescript-lua/releases/download/0.2/pslua-linux_x86_64.tar.gz -O - | tar -xz

      - name: Put pslua on PATH
        run: realpath pslua >> $GITHUB_PATH

      - name: what
        run: cat $GITHUB_PATH

      - name: Build and test
        run: ./test.sh
