name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Lua interpreter
        uses: leafo/gh-actions-lua@v11

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Set up Purescript and Spago
        run: |
          npm i -g purescript
          npm i -g spago

      - name: Build
        run: spago build

      - name: Test
        run: spago test
